Texture: fix AD support
wjakob/enoki pull request #18
Opened 2021-12-03 10:42 UTC by merlinND

- Enoki-side storage is now a tensor instead of an array
- `.value()` and `.tensor()` both return references so that `enable_grad()`, etc calls made on them have the expected effect
- Invalid value of `m_value` is now `Storage()` rather than `Storage(0)`

2021-12-03 11:21 UTC, merlinND commented on include/enoki/texture.h
> +        m_value = TensorXf(empty<Storage>(m_size), Dimension + 1, m_shape);
I think it's important to set the tensor dimensions correctly here, but I didn't know how to do it without also creating an array of the same size.

2021-12-04 21:38 UTC, wjakob requested changes
Hi Merlin, this looks great! I had a few small change requests, feel free to merge directly after applying them.

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +                    m_value.array() = replace_grad(Storage(0), value);
Actually, can we use `Storage()` instead of `Storage(0)` to indicate that the data has been migrated? The zero initialization was my mistake, that actually seems a little misleading.

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +        m_value.array() = Storage(0);
Zero initialization here makes sense in this case, because the texture is initially empty. However, I have a change request regarding zero-initialization below.

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +                if (m_value.array().size() != m_size) {
`.empty()`?

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +                    }
remove braces in this if statement (just two 1-liners)

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> -                if (grad_enabled(m_value, pos)) {
oops, does grad_enabled not work for tensors?

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +        m_value = TensorXf(empty<Storage>(m_size), Dimension + 1, m_shape);
using `empty` is suboptimal here, because it essentially wraps `cudaMalloc()`. Can you use `ek::zero`? In this case, Enoki creates an unevaluated literal constant array that doesn't use any GPU memory. In that case, the `m_value.array() = Storage(0);` in the `Texture` constructor can also go away.

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +        m_value.array() = Storage(0);
This line can then be removed also

2021-12-04 21:38 UTC, wjakob commented on include/enoki/texture.h
> +                    m_value.array() = replace_grad(Storage(0), value);
(we really do want enoki to error out with an "arithmetic involving unitialized value" exception if somebody then tries to access the underlying Enoki array)

2021-12-04 21:39 UTC, wjakob commented on include/enoki/texture.h
> +        m_value.array() = Storage(0);
Actually, this line can be removed after another requested change (see below)

2021-12-04 21:39 UTC, wjakob commented on include/enoki/texture.h
> +        m_value.array() = Storage(0);
(the zero-initialization of .array())

2021-12-05 17:43 UTC, merlinND commented on include/enoki/texture.h
> -                if (grad_enabled(m_value, pos)) {
Added `grad_enabled` and `set_grad_enabled` support for `Tensor` in C++, let me know if it's not done in the right place (I could also have added `set_grad_enabled_` directly in the `Tensor` class).

I've also added `zero_`, but it will only work for sizes `0` and `1` since there's no good mechanism to pass the full shape in C++ I think.

2021-12-05 17:48 UTC, merlinND commented on include/enoki/texture.h
> +                    m_value.array() = replace_grad(Storage(0), value);
I've tried to revert to uninitialized storage, but the following issue comes up: when `migrate=true` and gradients are enabled, `eval()` then tries to gather from `m_value.array()`, which is illegal.

My understanding from your original code was that the CUDA lookup would get the actual values, and then the call to `eval_enoki()` would gather from a legal zero-valued array to get the right gradients. The Enoki lookup would get optimized away, except for the AD part.

The Enoki lookup was already tested explicitly in your original code:
https://github.com/wjakob/enoki/blob/194de8397cd8e4ee1f5866cc1f5bdf2c05c65d70/tests/texture.cpp#L128


Do you want `eval_enoki()` to trigger `m_value` to be filled, or should we keep the zero initialization instead?
Note that unless there's a bug, accessing `.value()` or `.tensor()` _will_ fill the storage, so users should never see the uninitialized / zero-valued array anyway.

2021-12-05 19:00 UTC, wjakob approved these changes
Hi Merlin,

that's actually a great point. We want `gather()` from the migrated array to succeed, so it *needs* to have some value. Not sure if I was thinking of that case when developing the code originally, but it makes sense ;-) So please ignore my previous request to initialize to `Storage()`.

Thanks,
Wenzel

2021-12-06 09:11 UTC, wjakob commented
LGTM!

2021-12-06 09:54 UTC, merged

2021-12-06 10:05 UTC, wjakob commented
Thanks @merlinND !